### ISSUE TITLE
Question, How to clear the Fault ?

### ISSUE THREAD

**Issue by Amandabgotra** [matth-x/MicroOcpp#190]
I am using Function **ocpp_addErrorDataInput** and Fucntion **ocpp_addErrorCodeInput** to register a fault, But couldn't find a way to clear the Fault.
Is there already a way to clear the Fault or I've to create my own ?

**Comment by matth-x** [comment]
The OCPP lib regularly calls the Error Inputs to check if an error is happening or not. As long as the Input-function returns something, the OCPP lib assumes an error, when the Input-function returns only NULL, the OCPP lib sees the error as resolved.

Here's an example in the OpenEVSE project:

https://github.com/OpenEVSE/openevse_esp32_firmware/blob/827b64591e6ea6786b45403f65edff621235c73b/src/ocpp.cpp#L244-L249

It is for C++, but in C it works similar. Instead of the lambda function, a normal function needs to be passed to `ocpp_addErrorCodeInput` as the Error Input.

In the example, the Error-Input function checks if the EVSE class reports a temperature error via the condition `evse->getEvseState() == OPENEVSE_STATE_OVER_TEMPERATURE`. If that's the case, the Error-Input returns the corresponding OCPP 1.6 error code `HighTemperature` and if the EVSE class does not report a temperature error, the Error-Input returns NULL.

Feel free to reopen if you have follow-up questions.
